POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username" : "costeira",
    "password" : "password"
}

###

POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username" : "costeira",
    "password" : "wrongpassword"
}